# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20161021_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='apprenticeship',
            name='PrimaryFaculty',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='apprenticeship',
            name='SecondaryFaculty',
            field=models.CharField(default='', max_length=120),
        ),
    ]
