# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 01:29
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_auto_20161021_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('PF_First_Name', models.CharField(max_length=120, verbose_name='*First Name')),
                ('PF_Last_Name', models.CharField(max_length=120, verbose_name='*Last Name')),
                ('PF_Contact_Number', models.IntegerField(verbose_name='*Contact Number')),
                ('PF_Email', models.EmailField(max_length=254, verbose_name='*Email')),
                ('PF_Department', models.CharField(choices=[('Aerospace', 'Aerospace Engineering'), ('Applied Mathematics', 'Applied Mathematics'), ('Architectural', 'Architectural Engineering'), ('Chemical', 'Chemical Engineering'), ('Biological', 'Biological Engineering'), ('Civil', 'Civil Engineering'), ('Computer Science', 'Computer Science'), ('Electrical', 'Electrical Engineering'), ('Electrical and Computer', 'Electrical and Computer Engineering'), ('Egineering Physics', 'Engineering Physics'), ('Environmental', 'Environmental Engineering'), ('Mechanical', 'Mechanical Engineering'), ('Technology Arts and Media', 'Technology Arts and Media')], max_length=120, verbose_name='*Department')),
                ('PF_Communities', models.CharField(choices=[('select1', 'Yes'), ('select2', 'No')], max_length=120, verbose_name='Does the project have focus on Engineering for developing communities?')),
                ('SF_First_Name', models.CharField(max_length=120)),
                ('SF_Last_Name', models.CharField(max_length=120)),
                ('SF_Contact_Number', models.IntegerField()),
                ('SF_Email', models.EmailField(max_length=254)),
                ('SF_Department', models.CharField(choices=[('Aerospace', 'Aerospace Engineering'), ('Applied Mathematics', 'Applied Mathematics'), ('Architectural', 'Architectural Engineering'), ('Chemical', 'Chemical Engineering'), ('Biological', 'Biological Engineering'), ('Civil', 'Civil Engineering'), ('Computer Science', 'Computer Science'), ('Electrical', 'Electrical Engineering'), ('Electrical and Computer', 'Electrical and Computer Engineering'), ('Egineering Physics', 'Engineering Physics'), ('Environmental', 'Environmental Engineering'), ('Mechanical', 'Mechanical Engineering'), ('Technology Arts and Media', 'Technology Arts and Media')], max_length=120)),
                ('Appr_Title', models.CharField(max_length=120, verbose_name='*Apprenticeship Title')),
                ('Appr_Details', models.CharField(max_length=120, verbose_name='*Project Details (in brief)')),
                ('Appr_Project_Link1', models.CharField(max_length=120, verbose_name='Link to Project Details')),
                ('Appr_Project_Link2', models.FileField(default='settings.MEDIA_ROOT/default/temp.txt', storage=django.core.files.storage.FileSystemStorage(location=b'./media'), upload_to='Apprenticeship')),
                ('Appr_Special_Requirements', models.CharField(max_length=120, verbose_name='Special skillset required')),
                ('Appr_Departments', models.CharField(choices=[('Aerospace', 'Aerospace Engineering'), ('Applied Mathematics', 'Applied Mathematics'), ('Architectural', 'Architectural Engineering'), ('Chemical', 'Chemical Engineering'), ('Biological', 'Biological Engineering'), ('Civil', 'Civil Engineering'), ('Computer Science', 'Computer Science'), ('Electrical', 'Electrical Engineering'), ('Electrical and Computer', 'Electrical and Computer Engineering'), ('Egineering Physics', 'Engineering Physics'), ('Environmental', 'Environmental Engineering'), ('Mechanical', 'Mechanical Engineering'), ('Technology Arts and Media', 'Technology Arts and Media')], max_length=120)),
                ('Appr_Supervision_Level', models.CharField(choices=[('None', 'Very little supervision; student will need to work largely independently'), ('Moderate', 'Moderate amount of supervision and interaction with others'), ('A lot', 'Good deal of supervision; student will work as an integral part of a research team')], max_length=180)),
                ('Appr_Supervision_By', models.CharField(choices=[('Faculty', 'Supervision primarily by faculty supervisor'), ('Graduate Student', 'Supervision primarily by graduate students'), ('Combination', 'Supervision primarily a combination of faculty and graduate students')], max_length=180)),
                ('Appr_Nature_Of_Work', models.CharField(choices=[('theoretical', 'Nature of work is primarily theoretical, most work on paper/electronic medium'), ('experimental', 'Nature of work is primarily experimental, requiring hands-on work in a lab'), ('field based', 'Nature of work is primarily field based, requiring hands-on work in the field'), ('computer-related', 'Nature of work is primarily computer-related, involving coding/analysis'), ('combination', 'Nature of work is a combination of several types of work')], max_length=180)),
                ('Appr_Prior_Work', models.CharField(choices=[('None', 'No prior work; student will be starting from basic idea'), ('Some', 'Some prior work; student will build on work of others'), ('Well-established', 'Well-established body of work; student will refine/improved upon efforts of others')], max_length=180)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=80)),
                ('Last_Name', models.CharField(max_length=80)),
                ('Gender', models.CharField(choices=[('1', 'Male'), ('2', 'Female')], error_messages={'required': 'Please select a Gender type'}, max_length=25, verbose_name='*Gender')),
            ],
        ),
        migrations.DeleteModel(
            name='Apprenticeship',
        ),
        migrations.DeleteModel(
            name='PrimaryFaculty',
        ),
        migrations.DeleteModel(
            name='SecondFaculty',
        ),
    ]
