# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_auto_20161104_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='Username',
            field=models.CharField(default=None, max_length=180),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='SF_First_Name',
            field=models.CharField(max_length=120, verbose_name='Secondary Faculty, Firstname'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='SF_Last_Name',
            field=models.CharField(max_length=120, verbose_name='Secondary Faculty, Lastname'),
        ),
    ]
