# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_auto_20161104_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='SF_Contact_Number',
            field=models.IntegerField(default=0),
        ),
    ]
