# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_auto_20161104_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='SF_Contact_Number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
