# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0007_auto_20161104_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='Appr_Details',
            field=models.CharField(max_length=2000, verbose_name='*Project Details (in brief)'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='Appr_Nature_Of_Work',
            field=models.CharField(choices=[('theoretical', 'Nature of work is primarily theoretical, most work on paper/electronic medium'), ('experimental', 'Nature of work is primarily experimental, requiring hands-on work in a lab'), ('field based', 'Nature of work is primarily field based, requiring hands-on work in the field'), ('computer-related', 'Nature of work is primarily computer-related, involving coding/analysis'), ('combination', 'Nature of work is a combination of several types of work')], max_length=180, verbose_name='*Nature of Work'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='Appr_Prior_Work',
            field=models.CharField(choices=[('None', 'No prior work; student will be starting from basic idea'), ('Some', 'Some prior work; student will build on work of others'), ('Well-established', 'Well-established body of work; student will refine/improved upon efforts of others')], max_length=180, verbose_name='*Prior Work'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='Appr_Special_Requirements',
            field=models.CharField(max_length=120, verbose_name='*Special skillset required'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='Appr_Supervision_By',
            field=models.CharField(choices=[('Faculty', 'Supervision primarily by faculty supervisor'), ('Graduate Student', 'Supervision primarily by graduate students'), ('Combination', 'Supervision primarily a combination of faculty and graduate students')], max_length=180, verbose_name='*Supervision By'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='Appr_Supervision_Level',
            field=models.CharField(choices=[('None', 'Very little supervision; student will need to work largely independently'), ('Moderate', 'Moderate amount of supervision and interaction with others'), ('A lot', 'Good deal of supervision; student will work as an integral part of a research team')], max_length=180, verbose_name='*Supervision Level'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='PF_Communities',
            field=models.CharField(choices=[('select1', 'Yes'), ('select2', 'No')], max_length=120, verbose_name='*Does the project have focus on Engineering for developing communities?'),
        ),
    ]
