# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0008_auto_20161104_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Address_Line_1',
            field=models.CharField(default=None, max_length=200, verbose_name='*Address1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='Address_Line_2',
            field=models.CharField(default=None, max_length=200, verbose_name='*Address2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='City',
            field=models.CharField(default=None, max_length=80, verbose_name='City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='Country',
            field=models.CharField(default=None, max_length=80, verbose_name='*Country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='Race',
            field=models.CharField(choices=[('AI_AN', 'American Indian or Alaskan Native'), ('B_AA', 'Black or African-American'), ('NH_OPI', 'Native Hawaiian or other Pacific Islander'), ('A', 'Asian'), ('W', 'White'), ('O', 'Other'), ('DN', 'Do Not Wish to Provide')], default=None, max_length=25, verbose_name='*Race'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='State',
            field=models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], default=None, error_messages={'required': 'Please select a State'}, max_length=25, verbose_name='*State'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='Zip',
            field=models.CharField(default=None, max_length=5, verbose_name='*Zip'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='Appr_Departments',
            field=models.CharField(choices=[('Aerospace', 'Aerospace Engineering'), ('Applied Mathematics', 'Applied Mathematics'), ('Architectural', 'Architectural Engineering'), ('Chemical', 'Chemical Engineering'), ('Biological', 'Biological Engineering'), ('Civil', 'Civil Engineering'), ('Computer Science', 'Computer Science'), ('Electrical', 'Electrical Engineering'), ('Electrical and Computer', 'Electrical and Computer Engineering'), ('Egineering Physics', 'Engineering Physics'), ('Environmental', 'Environmental Engineering'), ('Mechanical', 'Mechanical Engineering'), ('Technology Arts and Media', 'Technology Arts and Media')], max_length=120, verbose_name='*Choose one or more departments'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='Appr_Special_Requirements',
            field=models.CharField(max_length=1000, verbose_name='*Special skillset required'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('D', 'Do Not Wish to Provide')], error_messages={'required': 'Please select a Gender type'}, max_length=25, verbose_name='*Gender'),
        ),
    ]
