# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 08:58
from __future__ import unicode_literals

import datetime
import django.core.files.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0009_auto_20161104_0412'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Anticipated_Graduation',
            field=models.DateField(default=datetime.datetime.now, verbose_name='*Anticipated Graduation Date'),
        ),
        migrations.AddField(
            model_name='student',
            name='Applied_Before',
            field=models.CharField(choices=[('1', 'True'), ('0', 'False')], default=None, max_length=20, verbose_name='Have you applied for Discovery Learning Apprenticeship before?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='Background_check',
            field=models.CharField(choices=[('1', 'True'), ('0', 'False'), ('2', 'Not Sure')], default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='Cover_Letter',
            field=models.FileField(default='settings.MEDIA_ROOT/default/temp.txt', storage=django.core.files.storage.FileSystemStorage(location=b'./media'), upload_to='Cover_Letter'),
        ),
        migrations.AddField(
            model_name='student',
            name='Discrimination_training',
            field=models.CharField(choices=[('1', 'True'), ('0', 'False'), ('2', 'Not Sure')], default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='Email',
            field=models.EmailField(default=None, max_length=254, verbose_name='*Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='First_Preference',
            field=models.CharField(choices=[(1, '1:Proj'), (2, '2:AES - Autonomous Robotic Planetary Exploration Simulator'), (3, '3:AES - Human-Automation Interaction for Space Exploration Missions'), (4, '4:AES - Adaptation of Human Orientation Perception to Altered Gravity'), (5, '5:'), (6, '6:'), (7, '7:'), (8, '8:'), (9, '9:'), (10, '10:'), (11, '11:'), (12, '12:'), (13, '13:sdf')], default=None, max_length=200, verbose_name='First Preference'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='Five_Preference',
            field=models.CharField(choices=[(1, '1:Proj'), (2, '2:AES - Autonomous Robotic Planetary Exploration Simulator'), (3, '3:AES - Human-Automation Interaction for Space Exploration Missions'), (4, '4:AES - Adaptation of Human Orientation Perception to Altered Gravity'), (5, '5:'), (6, '6:'), (7, '7:'), (8, '8:'), (9, '9:'), (10, '10:'), (11, '11:'), (12, '12:'), (13, '13:sdf')], default=None, max_length=200, verbose_name='Five Preference'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='Four_Preference',
            field=models.CharField(choices=[(1, '1:Proj'), (2, '2:AES - Autonomous Robotic Planetary Exploration Simulator'), (3, '3:AES - Human-Automation Interaction for Space Exploration Missions'), (4, '4:AES - Adaptation of Human Orientation Perception to Altered Gravity'), (5, '5:'), (6, '6:'), (7, '7:'), (8, '8:'), (9, '9:'), (10, '10:'), (11, '11:'), (12, '12:'), (13, '13:sdf')], default=None, max_length=200, verbose_name='Four Preference'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='GPA',
            field=models.FloatField(default=None, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(4.0)], verbose_name='*GPA'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='Level',
            field=models.CharField(choices=[('F', 'Freshman'), ('SO', 'Sophomore'), ('J', 'Junior'), ('SE', 'Senior'), ('FSE', '5th Year Senior')], default=None, max_length=50, verbose_name='*Level in school as of next fall'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='Phone',
            field=models.CharField(default=None, max_length=10, verbose_name='*Phone'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='Previous_Research',
            field=models.CharField(choices=[('1', 'True'), ('0', 'False')], default=None, max_length=20, verbose_name='Do you have previous research experience?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='Primary_Major',
            field=models.CharField(choices=[('None', 'None'), ('Aerospace', 'Aerospace Engineering'), ('Applied Mathematics', 'Applied Mathematics'), ('Architectural', 'Architectural Engineering'), ('Chemical', 'Chemical Engineering'), ('Biological', 'Biological Engineering'), ('Civil', 'Civil Engineering'), ('Computer Science', 'Computer Science'), ('Electrical', 'Electrical Engineering'), ('Electrical and Computer', 'Electrical and Computer Engineering'), ('Engineering Physics', 'Engineering Physics'), ('Environmental', 'Environmental Engineering'), ('Mechanical', 'Mechanical Engineering'), ('Technology Arts and Media', 'Technology Arts and Media')], default=None, max_length=50, verbose_name='*Primary Major'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='Resume',
            field=models.FileField(default='settings.MEDIA_ROOT/default/temp.txt', storage=django.core.files.storage.FileSystemStorage(location=b'./media'), upload_to='Resume'),
        ),
        migrations.AddField(
            model_name='student',
            name='SAddress_Line_1',
            field=models.CharField(default=None, max_length=200, verbose_name='*Summer Address1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='SAddress_Line_2',
            field=models.CharField(default=None, max_length=200, verbose_name='Summer Address2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='SCity',
            field=models.CharField(default=None, max_length=80, verbose_name='*Summer City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='SCountry',
            field=models.CharField(default='United States', max_length=80, verbose_name='*Summer Country'),
        ),
        migrations.AddField(
            model_name='student',
            name='SEmail',
            field=models.EmailField(default=None, max_length=254, verbose_name='*Summer Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='SPhone',
            field=models.CharField(default=None, max_length=10, verbose_name='*Summer Phone'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='SSN',
            field=models.CharField(default=None, max_length=4, verbose_name='Last four digits of your Social Security Number: (this will only be used to acess your background check information)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='SState',
            field=models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], default=None, error_messages={'required': 'Please select a State'}, max_length=25, verbose_name='*Summer State'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='SZip',
            field=models.CharField(default=None, max_length=5, verbose_name='*Summer Zip'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='Secondary_Major',
            field=models.CharField(choices=[('None', 'None'), ('Aerospace', 'Aerospace Engineering'), ('Applied Mathematics', 'Applied Mathematics'), ('Architectural', 'Architectural Engineering'), ('Chemical', 'Chemical Engineering'), ('Biological', 'Biological Engineering'), ('Civil', 'Civil Engineering'), ('Computer Science', 'Computer Science'), ('Electrical', 'Electrical Engineering'), ('Electrical and Computer', 'Electrical and Computer Engineering'), ('Engineering Physics', 'Engineering Physics'), ('Environmental', 'Environmental Engineering'), ('Mechanical', 'Mechanical Engineering'), ('Technology Arts and Media', 'Technology Arts and Media')], default=None, max_length=50, verbose_name='Secondary Major'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='Skills',
            field=models.CharField(default=None, max_length=300, verbose_name='Please list the three skills or qualifications that you feel make you a great candidate for the positions you selected. (Could be knowledge of a programming language, knowledge of a field, courses taken, personal characteristics, etc. If appropriate, note your match to requirements in job description. Please note responses are limited to 75 characters.)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='Skills_1',
            field=models.CharField(default=None, max_length=100, verbose_name='1. '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='Skills_2',
            field=models.CharField(default=None, max_length=100, verbose_name='2. '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='Skills_3',
            field=models.CharField(default=None, max_length=100, verbose_name='3. '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='Student_Id',
            field=models.IntegerField(default=None, verbose_name='*Student ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='Three_Preference',
            field=models.CharField(choices=[(1, '1:Proj'), (2, '2:AES - Autonomous Robotic Planetary Exploration Simulator'), (3, '3:AES - Human-Automation Interaction for Space Exploration Missions'), (4, '4:AES - Adaptation of Human Orientation Perception to Altered Gravity'), (5, '5:'), (6, '6:'), (7, '7:'), (8, '8:'), (9, '9:'), (10, '10:'), (11, '11:'), (12, '12:'), (13, '13:sdf')], default=None, max_length=200, verbose_name='Three Preference'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='Two_Preference',
            field=models.CharField(choices=[(1, '1:Proj'), (2, '2:AES - Autonomous Robotic Planetary Exploration Simulator'), (3, '3:AES - Human-Automation Interaction for Space Exploration Missions'), (4, '4:AES - Adaptation of Human Orientation Perception to Altered Gravity'), (5, '5:'), (6, '6:'), (7, '7:'), (8, '8:'), (9, '9:'), (10, '10:'), (11, '11:'), (12, '12:'), (13, '13:sdf')], default=None, max_length=200, verbose_name='Two Preference'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='Upload',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='Appr_Departments',
            field=models.CharField(choices=[('None', 'None'), ('Aerospace', 'Aerospace Engineering'), ('Applied Mathematics', 'Applied Mathematics'), ('Architectural', 'Architectural Engineering'), ('Chemical', 'Chemical Engineering'), ('Biological', 'Biological Engineering'), ('Civil', 'Civil Engineering'), ('Computer Science', 'Computer Science'), ('Electrical', 'Electrical Engineering'), ('Electrical and Computer', 'Electrical and Computer Engineering'), ('Engineering Physics', 'Engineering Physics'), ('Environmental', 'Environmental Engineering'), ('Mechanical', 'Mechanical Engineering'), ('Technology Arts and Media', 'Technology Arts and Media')], max_length=120, verbose_name='*Choose one or more departments'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='PF_Department',
            field=models.CharField(choices=[('None', 'None'), ('Aerospace', 'Aerospace Engineering'), ('Applied Mathematics', 'Applied Mathematics'), ('Architectural', 'Architectural Engineering'), ('Chemical', 'Chemical Engineering'), ('Biological', 'Biological Engineering'), ('Civil', 'Civil Engineering'), ('Computer Science', 'Computer Science'), ('Electrical', 'Electrical Engineering'), ('Electrical and Computer', 'Electrical and Computer Engineering'), ('Engineering Physics', 'Engineering Physics'), ('Environmental', 'Environmental Engineering'), ('Mechanical', 'Mechanical Engineering'), ('Technology Arts and Media', 'Technology Arts and Media')], max_length=120, verbose_name='*Department'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='SF_Department',
            field=models.CharField(choices=[('None', 'None'), ('Aerospace', 'Aerospace Engineering'), ('Applied Mathematics', 'Applied Mathematics'), ('Architectural', 'Architectural Engineering'), ('Chemical', 'Chemical Engineering'), ('Biological', 'Biological Engineering'), ('Civil', 'Civil Engineering'), ('Computer Science', 'Computer Science'), ('Electrical', 'Electrical Engineering'), ('Electrical and Computer', 'Electrical and Computer Engineering'), ('Engineering Physics', 'Engineering Physics'), ('Environmental', 'Environmental Engineering'), ('Mechanical', 'Mechanical Engineering'), ('Technology Arts and Media', 'Technology Arts and Media')], max_length=120),
        ),
        migrations.AlterField(
            model_name='student',
            name='Address_Line_2',
            field=models.CharField(max_length=200, verbose_name='Address2'),
        ),
        migrations.AlterField(
            model_name='student',
            name='City',
            field=models.CharField(max_length=80, verbose_name='*City'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Country',
            field=models.CharField(default='United States', max_length=80, verbose_name='*Country'),
        ),
        migrations.AlterField(
            model_name='student',
            name='First_Name',
            field=models.CharField(max_length=80, verbose_name='*First Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Last_Name',
            field=models.CharField(max_length=80, verbose_name='*Last Name'),
        ),
    ]
