# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0011_auto_20161104_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Applied_Before',
            field=models.CharField(choices=[('1', 'True'), ('0', 'False')], max_length=20, verbose_name='*Have you applied for Discovery Learning Apprenticeship before?'),
        ),
        migrations.AlterField(
            model_name='student',
            name='First_Preference',
            field=models.CharField(choices=[(b'1', '1:Proj'), (b'2', '2:AES - Autonomous Robotic Planetary Exploration Simulator'), (b'3', '3:AES - Human-Automation Interaction for Space Exploration Missions'), (b'4', '4:AES - Adaptation of Human Orientation Perception to Altered Gravity'), (b'5', '5:'), (b'6', '6:'), (b'7', '7:'), (b'8', '8:'), (b'9', '9:'), (b'10', '10:'), (b'11', '11:'), (b'12', '12:'), (b'13', '13:sdf')], max_length=200, verbose_name='*First Preference'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Five_Preference',
            field=models.CharField(choices=[(b'1', '1:Proj'), (b'2', '2:AES - Autonomous Robotic Planetary Exploration Simulator'), (b'3', '3:AES - Human-Automation Interaction for Space Exploration Missions'), (b'4', '4:AES - Adaptation of Human Orientation Perception to Altered Gravity'), (b'5', '5:'), (b'6', '6:'), (b'7', '7:'), (b'8', '8:'), (b'9', '9:'), (b'10', '10:'), (b'11', '11:'), (b'12', '12:'), (b'13', '13:sdf')], max_length=200, verbose_name='Five Preference'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Four_Preference',
            field=models.CharField(choices=[(b'1', '1:Proj'), (b'2', '2:AES - Autonomous Robotic Planetary Exploration Simulator'), (b'3', '3:AES - Human-Automation Interaction for Space Exploration Missions'), (b'4', '4:AES - Adaptation of Human Orientation Perception to Altered Gravity'), (b'5', '5:'), (b'6', '6:'), (b'7', '7:'), (b'8', '8:'), (b'9', '9:'), (b'10', '10:'), (b'11', '11:'), (b'12', '12:'), (b'13', '13:sdf')], max_length=200, verbose_name='Four Preference'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Phone',
            field=models.IntegerField(max_length=10, verbose_name='*Phone'),
        ),
        migrations.AlterField(
            model_name='student',
            name='SPhone',
            field=models.IntegerField(max_length=10, verbose_name='*Summer Phone'),
        ),
        migrations.AlterField(
            model_name='student',
            name='SSN',
            field=models.IntegerField(max_length=4, verbose_name='*Last four digits of your Social Security Number: (this will only be used to acess your background check information)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Three_Preference',
            field=models.CharField(choices=[(b'1', '1:Proj'), (b'2', '2:AES - Autonomous Robotic Planetary Exploration Simulator'), (b'3', '3:AES - Human-Automation Interaction for Space Exploration Missions'), (b'4', '4:AES - Adaptation of Human Orientation Perception to Altered Gravity'), (b'5', '5:'), (b'6', '6:'), (b'7', '7:'), (b'8', '8:'), (b'9', '9:'), (b'10', '10:'), (b'11', '11:'), (b'12', '12:'), (b'13', '13:sdf')], max_length=200, verbose_name='Three Preference'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Two_Preference',
            field=models.CharField(choices=[(b'1', '1:Proj'), (b'2', '2:AES - Autonomous Robotic Planetary Exploration Simulator'), (b'3', '3:AES - Human-Automation Interaction for Space Exploration Missions'), (b'4', '4:AES - Adaptation of Human Orientation Perception to Altered Gravity'), (b'5', '5:'), (b'6', '6:'), (b'7', '7:'), (b'8', '8:'), (b'9', '9:'), (b'10', '10:'), (b'11', '11:'), (b'12', '12:'), (b'13', '13:sdf')], max_length=200, verbose_name='Two Preference'),
        ),
    ]
