# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 00:07
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personal', '0012_auto_20161104_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(verbose_name='*Student/Faculties Unique Id')),
                ('uid', models.CharField(choices=[(0, 'Student'), (1, 'Faculty'), (2, 'Admin'), (3, 'CAES Staff')], max_length=5, verbose_name='*Role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='First_Preference',
            field=models.CharField(choices=[('0', None), (b'14', '14:APPM - Machine Learning for earthquake prediction'), (b'15', '15:Merton\u2019s Problem with Human Capital Investment'), (b'16', '16:Autonomous Robotic Planetary Exploration Simulator'), (b'17', '17:GPS/GNSS Receiver Design/Development for Space Applications'), (b'18', '18:Throw Away Accounts'), (b'19', '19:Social norms in online communities')], max_length=200, verbose_name='*First Preference'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Five_Preference',
            field=models.CharField(choices=[('0', None), (b'14', '14:APPM - Machine Learning for earthquake prediction'), (b'15', '15:Merton\u2019s Problem with Human Capital Investment'), (b'16', '16:Autonomous Robotic Planetary Exploration Simulator'), (b'17', '17:GPS/GNSS Receiver Design/Development for Space Applications'), (b'18', '18:Throw Away Accounts'), (b'19', '19:Social norms in online communities')], max_length=200, verbose_name='Five Preference'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Four_Preference',
            field=models.CharField(choices=[('0', None), (b'14', '14:APPM - Machine Learning for earthquake prediction'), (b'15', '15:Merton\u2019s Problem with Human Capital Investment'), (b'16', '16:Autonomous Robotic Planetary Exploration Simulator'), (b'17', '17:GPS/GNSS Receiver Design/Development for Space Applications'), (b'18', '18:Throw Away Accounts'), (b'19', '19:Social norms in online communities')], max_length=200, verbose_name='Four Preference'),
        ),
        migrations.AlterField(
            model_name='student',
            name='GPA',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(4.0)], verbose_name='*GPA (Should be between 0 to 4)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Phone',
            field=models.IntegerField(verbose_name='*Phone'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Race',
            field=models.CharField(choices=[('None', 'None'), ('AI_AN', 'American Indian or Alaskan Native'), ('B_AA', 'Black or African-American'), ('NH_OPI', 'Native Hawaiian or other Pacific Islander'), ('A', 'Asian'), ('W', 'White'), ('O', 'Other'), ('DN', 'Do Not Wish to Provide')], max_length=25, verbose_name='*Race'),
        ),
        migrations.AlterField(
            model_name='student',
            name='SPhone',
            field=models.IntegerField(verbose_name='*Summer Phone'),
        ),
        migrations.AlterField(
            model_name='student',
            name='SSN',
            field=models.IntegerField(verbose_name='*Last four digits of your Social Security Number: (this will only be used to acess your background check information)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='SState',
            field=models.CharField(choices=[('NN', ''), ('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], error_messages={'required': 'Please select a State'}, max_length=25, verbose_name='*Summer State'),
        ),
        migrations.AlterField(
            model_name='student',
            name='State',
            field=models.CharField(choices=[('NN', ''), ('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], error_messages={'required': 'Please select a State'}, max_length=25, verbose_name='*State'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Three_Preference',
            field=models.CharField(choices=[('0', None), (b'14', '14:APPM - Machine Learning for earthquake prediction'), (b'15', '15:Merton\u2019s Problem with Human Capital Investment'), (b'16', '16:Autonomous Robotic Planetary Exploration Simulator'), (b'17', '17:GPS/GNSS Receiver Design/Development for Space Applications'), (b'18', '18:Throw Away Accounts'), (b'19', '19:Social norms in online communities')], max_length=200, verbose_name='Three Preference'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Two_Preference',
            field=models.CharField(choices=[('0', None), (b'14', '14:APPM - Machine Learning for earthquake prediction'), (b'15', '15:Merton\u2019s Problem with Human Capital Investment'), (b'16', '16:Autonomous Robotic Planetary Exploration Simulator'), (b'17', '17:GPS/GNSS Receiver Design/Development for Space Applications'), (b'18', '18:Throw Away Accounts'), (b'19', '19:Social norms in online communities')], max_length=200, verbose_name='Two Preference'),
        ),
    ]
