# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 04:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0013_auto_20161105_0007'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
