# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0015_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='SPhone',
            field=models.IntegerField(null=True, verbose_name='*Summer Phone'),
        ),
    ]
