# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 00:13
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0016_auto_20161105_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='Appr_Departments',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('None', 'None'), ('Aerospace', 'Aerospace Engineering'), ('Applied Mathematics', 'Applied Mathematics'), ('Architectural', 'Architectural Engineering'), ('Chemical', 'Chemical Engineering'), ('Biological', 'Biological Engineering'), ('Civil', 'Civil Engineering'), ('Computer Science', 'Computer Science'), ('Electrical', 'Electrical Engineering'), ('Electrical and Computer', 'Electrical and Computer Engineering'), ('Engineering Physics', 'Engineering Physics'), ('Environmental', 'Environmental Engineering'), ('Mechanical', 'Mechanical Engineering'), ('Technology Arts and Media', 'Technology Arts and Media')], max_length=120, verbose_name='*Choose one or more departments'),
        ),
    ]
