# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 00:21
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0017_auto_20161112_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='First_Preference',
            field=models.CharField(choices=[('0', None), (b'14', '14:APPM - Machine Learning for earthquake prediction'), (b'15', '15:Merton\u2019s Problem with Human Capital Investment'), (b'16', '16:Autonomous Robotic Planetary Exploration Simulator'), (b'17', '17:GPS/GNSS Receiver Design/Development for Space Applications'), (b'18', '18:Throw Away Accounts'), (b'19', '19:Social norms in online communities'), (b'20', '20:Title')], max_length=200, verbose_name='*First Preference'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Five_Preference',
            field=models.CharField(choices=[('0', None), (b'14', '14:APPM - Machine Learning for earthquake prediction'), (b'15', '15:Merton\u2019s Problem with Human Capital Investment'), (b'16', '16:Autonomous Robotic Planetary Exploration Simulator'), (b'17', '17:GPS/GNSS Receiver Design/Development for Space Applications'), (b'18', '18:Throw Away Accounts'), (b'19', '19:Social norms in online communities'), (b'20', '20:Title')], max_length=200, verbose_name='Five Preference'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Four_Preference',
            field=models.CharField(choices=[('0', None), (b'14', '14:APPM - Machine Learning for earthquake prediction'), (b'15', '15:Merton\u2019s Problem with Human Capital Investment'), (b'16', '16:Autonomous Robotic Planetary Exploration Simulator'), (b'17', '17:GPS/GNSS Receiver Design/Development for Space Applications'), (b'18', '18:Throw Away Accounts'), (b'19', '19:Social norms in online communities'), (b'20', '20:Title')], max_length=200, verbose_name='Four Preference'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Race',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('None', 'None'), ('AI_AN', 'American Indian or Alaskan Native'), ('B_AA', 'Black or African-American'), ('NH_OPI', 'Native Hawaiian or other Pacific Islander'), ('A', 'Asian'), ('W', 'White'), ('O', 'Other'), ('DN', 'Do Not Wish to Provide')], max_length=100, verbose_name='*Race'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Three_Preference',
            field=models.CharField(choices=[('0', None), (b'14', '14:APPM - Machine Learning for earthquake prediction'), (b'15', '15:Merton\u2019s Problem with Human Capital Investment'), (b'16', '16:Autonomous Robotic Planetary Exploration Simulator'), (b'17', '17:GPS/GNSS Receiver Design/Development for Space Applications'), (b'18', '18:Throw Away Accounts'), (b'19', '19:Social norms in online communities'), (b'20', '20:Title')], max_length=200, verbose_name='Three Preference'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Two_Preference',
            field=models.CharField(choices=[('0', None), (b'14', '14:APPM - Machine Learning for earthquake prediction'), (b'15', '15:Merton\u2019s Problem with Human Capital Investment'), (b'16', '16:Autonomous Robotic Planetary Exploration Simulator'), (b'17', '17:GPS/GNSS Receiver Design/Development for Space Applications'), (b'18', '18:Throw Away Accounts'), (b'19', '19:Social norms in online communities'), (b'20', '20:Title')], max_length=200, verbose_name='Two Preference'),
        ),
    ]
