# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 23:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0018_auto_20161112_0021'),
        ('personal', '0018_auto_20161112_0146'),
    ]

    operations = [
    ]
