# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 23:18
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0019_merge_20161116_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='Min_GPA',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(4.0)], verbose_name='*GPA (Should be between 0 to 4)'),
        ),
    ]
