# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0020_auto_20161116_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='P1_Req1',
            field=models.CharField(choices=[('1', 'True'), ('0', 'False')], default=False, max_length=50, verbose_name='Title Req1'),
        ),
        migrations.AddField(
            model_name='student',
            name='P1_Req2',
            field=models.CharField(choices=[('1', 'True'), ('0', 'False')], default=False, max_length=50, verbose_name='Title Req1'),
        ),
        migrations.AddField(
            model_name='student',
            name='P1_Req3',
            field=models.CharField(choices=[('1', 'True'), ('0', 'False')], default=False, max_length=50, verbose_name='Title Req1'),
        ),
        migrations.AddField(
            model_name='student',
            name='P2_Req1',
            field=models.CharField(choices=[('1', 'True'), ('0', 'False')], default=False, max_length=50, verbose_name='Title Req1'),
        ),
        migrations.AddField(
            model_name='student',
            name='P2_Req2',
            field=models.CharField(choices=[('1', 'True'), ('0', 'False')], default=False, max_length=50, verbose_name='Title Req1'),
        ),
        migrations.AddField(
            model_name='student',
            name='P2_Req3',
            field=models.CharField(choices=[('1', 'True'), ('0', 'False')], default=False, max_length=50, verbose_name='Title Req1'),
        ),
        migrations.AddField(
            model_name='student',
            name='P3_Req1',
            field=models.CharField(choices=[('1', 'True'), ('0', 'False')], default=False, max_length=50, verbose_name='Title Req1'),
        ),
        migrations.AddField(
            model_name='student',
            name='P3_Req2',
            field=models.CharField(choices=[('1', 'True'), ('0', 'False')], default=False, max_length=50, verbose_name='Title Req1'),
        ),
        migrations.AddField(
            model_name='student',
            name='P3_Req3',
            field=models.CharField(choices=[('1', 'True'), ('0', 'False')], default=False, max_length=50, verbose_name='Title Req1'),
        ),
        migrations.AddField(
            model_name='student',
            name='P4_Req1',
            field=models.CharField(choices=[('1', 'True'), ('0', 'False')], default=False, max_length=50, verbose_name='Title Req1'),
        ),
        migrations.AddField(
            model_name='student',
            name='P4_Req2',
            field=models.CharField(choices=[('1', 'True'), ('0', 'False')], default=False, max_length=50, verbose_name='Title Req1'),
        ),
        migrations.AddField(
            model_name='student',
            name='P4_Req3',
            field=models.CharField(choices=[('1', 'True'), ('0', 'False')], default=False, max_length=50, verbose_name='Title Req1'),
        ),
        migrations.AddField(
            model_name='student',
            name='P5_Req1',
            field=models.CharField(choices=[('1', 'True'), ('0', 'False')], default=False, max_length=50, verbose_name='Title Req1'),
        ),
        migrations.AddField(
            model_name='student',
            name='P5_Req2',
            field=models.CharField(choices=[('1', 'True'), ('0', 'False')], default=False, max_length=50, verbose_name='Title Req1'),
        ),
        migrations.AddField(
            model_name='student',
            name='P5_Req3',
            field=models.CharField(choices=[('1', 'True'), ('0', 'False')], default=False, max_length=50, verbose_name='Title Req1'),
        ),
    ]
