# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0021_auto_20161119_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Race',
            field=models.CharField(choices=[('None', 'None'), ('AI_AN', 'American Indian or Alaskan Native'), ('B_AA', 'Black or African-American'), ('NH_OPI', 'Native Hawaiian or other Pacific Islander'), ('A', 'Asian'), ('W', 'White'), ('O', 'Other'), ('DN', 'Do Not Wish to Provide')], max_length=100, verbose_name='*Race'),
        ),
    ]
