# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0022_auto_20161119_0254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='Student_Id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='*Student ID'),
        ),
    ]
